name: Enforce Repo Rules

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  enforce-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get actor and branch
        id: meta
        run: |
          echo "actor=${GITHUB_ACTOR}" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Detect file changes
        id: changes
        run: |
          git diff --name-status HEAD~1 HEAD > changes.txt
          cat changes.txt

      - name: Enforce rules
        run: |
          ACTOR="${{ steps.meta.outputs.actor }}"
          BRANCH="${{ steps.meta.outputs.branch }}"
          echo "👤 Actor: $ACTOR"
          echo "🌿 Branch: $BRANCH"

          if [[ "$ACTOR" == "mildhasvoided" ]]; then
            echo "✅ mildhasvoided is exempt. Skipping enforcement."
            exit 0
          fi

          if [[ "$BRANCH" == "main" || "$BRANCH" == "experimental" ]]; then
            echo "❌ $ACTOR is not allowed to edit $BRANCH"
            exit 1
          fi

          while IFS=$'\t' read -r status file; do
            if [[ "$status" == "D" ]]; then
              echo "❌ $ACTOR tried to delete $file — not allowed"
              exit 1
            fi

            if [[ "$BRANCH" == "modlist" ]]; then
              if [[ "$status" == "M" || "$status" == "A" ]]; then
                if [[ "$file" != "$ACTOR/"* ]]; then
                  echo "❌ $ACTOR can only modify files in their own folder on modlist"
                  exit 1
                fi
              fi
            fi
          done < changes.txt

          echo "✅ All checks passed"
