name: Owner-Only Enforcement

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  enforce-owner-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get actor and branch
        id: meta
        run: |
          echo "actor=${GITHUB_ACTOR}" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Detect file changes
        run: |
          git diff --name-status HEAD~1 HEAD > changes.txt
          cat changes.txt

      - name: Enforce owner-only access
        run: |
          ACTOR="${{ steps.meta.outputs.actor }}"
          echo "👤 Actor: $ACTOR"

          if [[ "$ACTOR" != "mildhasvoided" ]]; then
            echo "❌ Unauthorized modification attempt by $ACTOR"
            exit 1
          fi

          echo "✅ Authorized push by $ACTOR"
